name: Build PECL Extension
run-name: Build PECL Extension ${{ inputs.extension }}-${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      extension:
        description: 'PECL extension to build'
        required: true
      version:
        description: 'PECL extension version to build'
        required: true
jobs:
  build:
    name: ${{github.event.inputs.extension}}-${{github.event.inputs.version}} (${{matrix.version}}, ${{matrix.arch}}, ${{matrix.ts}})
    strategy:
      fail-fast: false
      matrix:
        version: ['8.3', '8.2', '8.1', '8.0']
        arch: [x64, x86]
        ts: [nts, ts]
    runs-on: windows-2019
    steps:
      - name: Checkout php-ftw
        uses: actions/checkout@v4

      - name: Fetch package
        run: powershell src/pecl/fetch-package.ps1 ${{github.event.inputs.extension}} ${{github.event.inputs.version}}

      - name: Compute virtual inputs
        id: virtuals
        run: powershell src/pecl/pecl.ps1 ${{matrix.version}} ${{matrix.arch}} ${{matrix.ts}} ${{github.event.inputs.extension}}

      - name: Normalize package folder structure
        if: ${{steps.virtuals.outputs.subfolder != ''}}
        run: powershell src/pecl/normalize-package.ps1 ${{github.event.inputs.extension}} ${{github.event.inputs.version}} ${{steps.virtuals.outputs.subfolder}}

      - name: Setup PHP
        id: setup-php
        uses: php/setup-php-sdk@v0.8
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
          deps: ${{steps.virtuals.outputs.libs}}

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
          sdk: ${{steps.setup-php.outputs.winsdk}}

      - name: Install PECL dependency libs
        run: powershell src/pecl/install-pecl-deps-libs.ps1 ${{steps.virtuals.outputs.vs}} ${{matrix.arch}}

      - name: Rename PECL dependency lib LICENSE files
        run: powershell src/pecl/rename-license.ps1

      - name: Build and install dependency extensions
        run: powershell src/pecl/build-install-deps.ps1 ${{steps.setup-php.outputs.prefix}}

      - name: phpize
        run: powershell src/pecl/phpize.ps1 ${{github.event.inputs.extension}} ${{github.event.inputs.version}} ${{matrix.version}} ${{matrix.ts}} ${{steps.virtuals.outputs.vs}} ${{matrix.arch}}

      - name: configure
        run: powershell src/pecl/configure.ps1 ${{github.event.inputs.extension}} ${{github.event.inputs.version}} ${{matrix.version}} ${{matrix.ts}} ${{steps.virtuals.outputs.vs}} ${{matrix.arch}} ${{steps.virtuals.outputs.config}}

      - name: make
        run: powershell src/pecl/make.ps1 ${{github.event.inputs.extension}} ${{github.event.inputs.version}} ${{matrix.version}} ${{matrix.ts}} ${{steps.virtuals.outputs.vs}} ${{matrix.arch}}

      - name: Package
        run: powershell src/pecl/package.ps1 ${{github.event.inputs.extension}} ${{github.event.inputs.version}} ${{matrix.version}} ${{matrix.ts}} ${{steps.virtuals.outputs.vs}} ${{matrix.arch}} ${{steps.virtuals.outputs.builddir}} ${{steps.virtuals.outputs.docs}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: install
